spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL:?DB_URL is required}
    username: ${DB_USERNAME:?DB_USERNAME is required}
    password: ${DB_PASSWORD:?DB_PASSWORD is required}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    url: ${API_GATEWAY:http://apigateway-service:8000}

external:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8080}
  pet-service:
    url: ${PET_SERVICE_URL:http://pet-service:8080}
