spring:
  application:
    name: social-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

server:
  port: 8083
  shutdown: graceful

# Swagger에서 사용할 Gateway 주소 변수는 남겨둠 (Java Config에서 주입받기 위함)
openapi:
  service:
    url: ${API_GATEWAY}

external:
  user-service:
    url: ${USER_SERVICE_URL}
  pet-service:
    url: ${PET_SERVICE_URL}