spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # Prod 환경에서는 반드시 환경변수(OS Env)로 주입받아야 함
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # 배포 시엔 스키마 자동 변경 방지 (검증만 수행)
    show-sql: false      # 운영 로그 절약
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 배포 환경 외부 서비스 주소 (K8s Service Name 사용 권장)
openapi:
  service:
    # K8s Gateway Service 주소 (예: http://gateway-service.default.svc.cluster.local:8000)
    url: ${API_GATEWAY:http://apigateway-service:8000}

external:
  user-service:
    # User Service K8s 내부 주소
    url: ${USER_SERVICE_URL:http://user-service:8080}
  pet-service:
    # Pet Service K8s 내부 주소
    url: ${PET_SERVICE_URL:http://pet-service:8080}