spring:
  application:
    name: social-service

  # Feign Client 공통 설정
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

server:
  port: 8083
  shutdown: graceful

# 기본 프로필 설정 (기본적으로 dev 실행)
spring.profiles.active: dev